apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: appcursomc
  namespace: myprojectcursomc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appcursomc
      tier: backend
  template:
    metadata:
      labels:
        app: appcursomc
        tier: backend
    spec:
      containers:
        - name: appcursomc
          image: 'marcosseibert2389/appcursomc:1.0.0'
          imagePullPolicy: IfNotPresent
          ports:
            - name: tcp
              containerPort: 8888
              protocol: TCP
          env:
            - name: ENV_PORT
              valueFrom:
                configMapKeyRef:
                  key: ENV_PORT
                  name: cursomc-config
            - name: ENV_CTX_PATH
              valueFrom:
                configMapKeyRef:
                  key: ENV_CTX_PATH
                  name: cursomc-config
            - name: ENV_DBUSER
              valueFrom:
                secretKeyRef:
                  name: cursomc-secret
                  key: username
            - name: ENV_DBPWD
              valueFrom:
                secretKeyRef:
                  name: cursomc-secret
                  key: password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: cursomc-secret
                  key: jwtsecret
      resources:
        limits:
          cpu: 250m
          memory: 512Mi
        requests:
          cpu: 125m
          memory: 256Mi
---
kind: Service
apiVersion: v1
metadata:
  name: appcursomc
  namespace: myprojectcursomc
spec:
  ports:
    - name: appcursomc
      protocol: TCP
      port: 9999
      targetPort: 8888
  selector:
    app: appcursomc
  type: ClusterIP
